export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCTS_LIST_ELEM = 'UPDATE_PRODUCTS_LIST_ELEM';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ERASE_LIST = 'ERASE_LIST';

export const ADD_LIST = 'ADD_LIST';
export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_LIST_END = 'FETCH_LIST_END';
export const REMOVE_LIST = 'REMOVE_LIST';
export const UPDATE_SHOPPING_LIST_ELEMENT = 'UPDATE_SHOPPING_LIST_ELEMENT';
export const ERASE_SHOPPING_LISTS = 'ERASE_SHOPPING_LISTS';


export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_ERASE_ERROR = 'AUTH_ERASE_ERROR';
export const AUTH_SUCCESSFULLY = 'AUTH_SUCCESSFULLY';
export const AUTH_USER_DATA_UPDATED = 'AUTH_USER_DATA_UPDATED';
export const AUTH_USER_EMAIL_UPDATED = 'AUTH_USER_EMAIL_UPDATED';
export const AUTH_USER_PASSWORD_UPDATED = 'AUTH_USER_PASSWORD_UPDATED';
export const SIGN_OUT_SUCCESSFULLY = 'SIGN_OUT_SUCCESSFULLY';
export const AUTH_PASSWORD_RESET_SUCCESSFULLY = 'AUTH_PASSWORD_RESET_SUCCESSFULLY';

export const LOADING_OVER = 'LOADING_OVER';
export const LOADING_START = 'LOADING_START';
export const NOTIFICATION_ADDED = 'NOTIFICATION_ADDED';
export const NOTIFICATION_REMOVED = 'NOTIFICATION_REMOVED';
