export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const CHECK_PRODUCT = 'CHECK_PRODUCT';
export const UNCHECK_PRODUCT = 'UNCHECK_PRODUCT';
export const REMOVE_CHECKED = 'REMOVE_CHECKED';